In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt ##menampilkan library

In [30]:
data1 = pd.read_csv('K01_heart_disease.csv')
data1 ##menampilkan data set

Age Sex ChestPainType  RestingBP  Cholesterol  FastingBS RestingECG  \
0     40   M           ATA        140          289          0     Normal   
1     49   F           NAP        160          180          0     Normal   
2     37   M           ATA        130          283          0         ST   
3     48   F           ASY        138          214          0     Normal   
4     54   M           NAP        150          195          0     Normal   
..   ...  ..           ...        ...          ...        ...        ...   
913   45   M            TA        110          264          0     Normal   
914   68   M           ASY        144          193          1     Normal   
915   57   M           ASY        130          131          0     Normal   
916   57   F           ATA        130          236          0        LVH   
917   38   M           NAP        138          175          0     Normal   

     MaxHR ExerciseAngina  Oldpeak ST_Slope  HeartDisease  
0      172              N      0.0       Up             0  
1      156              N      1.0     Flat             1  
2       98              N      0.0       Up             0  
3      108              Y      1.5     Flat             1  
4      122              N      0.0       Up             0  
..     ...            ...      ...      ...           ...  
913    132              N      1.2     Flat             1  
914    141              N      3.4     Flat             1  
915    115              Y      1.2     Flat             1  
916    174              N      0.0     Flat             1  
917    173              N      0.0       Up             0  

[918 rows x 12 columns]

In [31]:
data1.info() ##menampilkan informasi tentang objek data1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB


In [32]:
categorical_features = [feature for feature in data1.columns
                       if data1[feature].dtypes == "O"]
data1[categorical_features] ## Memilih Fitur Kategorikal dari DataFrame

Sex ChestPainType RestingECG ExerciseAngina ST_Slope
0     M           ATA     Normal              N       Up
1     F           NAP     Normal              N     Flat
2     M           ATA         ST              N       Up
3     F           ASY     Normal              Y     Flat
4     M           NAP     Normal              N       Up
..   ..           ...        ...            ...      ...
913   M            TA     Normal              N     Flat
914   M           ASY     Normal              N     Flat
915   M           ASY     Normal              Y     Flat
916   F           ATA        LVH              N     Flat
917   M           NAP     Normal              N       Up

[918 rows x 5 columns]

In [33]:
for i in categorical_features:
    print(data1[i].unique()) ##menampilkan nilai unik dari fitur-fitur kategorikal dalam sebuah dataset

['M' 'F']
['ATA' 'NAP' 'ASY' 'TA']
['Normal' 'ST' 'LVH']
['N' 'Y']
['Up' 'Flat' 'Down']


In [34]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

for feature in categorical_features:
    print(data1[feature].unique())
    data1[feature] = label_encoder.fit_transform(data1[feature])
    print(data1[feature].unique()) ##untuk mengonversi data kategorikal dalam sebuah dataset menjadi data numerik

['M' 'F']
[1 0]
['ATA' 'NAP' 'ASY' 'TA']
[1 2 0 3]
['Normal' 'ST' 'LVH']
[1 2 0]
['N' 'Y']
[0 1]
['Up' 'Flat' 'Down']
[2 1 0]


In [35]:
data1 ##menampilkan data

Age  Sex  ChestPainType  RestingBP  Cholesterol  FastingBS  RestingECG  \
0     40    1              1        140          289          0           1   
1     49    0              2        160          180          0           1   
2     37    1              1        130          283          0           2   
3     48    0              0        138          214          0           1   
4     54    1              2        150          195          0           1   
..   ...  ...            ...        ...          ...        ...         ...   
913   45    1              3        110          264          0           1   
914   68    1              0        144          193          1           1   
915   57    1              0        130          131          0           1   
916   57    0              1        130          236          0           0   
917   38    1              2        138          175          0           1   

     MaxHR  ExerciseAngina  Oldpeak  ST_Slope  HeartDisease  
0      172               0      0.0         2             0  
1      156               0      1.0         1             1  
2       98               0      0.0         2             0  
3      108               1      1.5         1             1  
4      122               0      0.0         2             0  
..     ...             ...      ...       ...           ...  
913    132               0      1.2         1             1  
914    141               0      3.4         1             1  
915    115               1      1.2         1             1  
916    174               0      0.0         1             1  
917    173               0      0.0         2             0  

[918 rows x 12 columns]

In [36]:
x = data1.drop(['Age', 'HeartDisease'], axis = 1) #berisi semua fitur input untuk model (variabel independen).
y = data1['Age'] #y berisi data target (output) yang ingin diprediksi (variabel dependen).

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0) ##data untuk membantu memvalidasi performa model dan mengurangi risiko overfitting.

In [38]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train) ##digunakan untuk membuat model klasifikasi Naive Bayes berbasis distribusi Gaussian.

GaussianNB()

In [39]:
y_pred_train = model.predict(x_train) ##digunakan untuk mengukur seberapa baik model memprediksi data pelatihan. Hal ini bisa membantu mendeteksi masalah overfitting jika model sangat akurat di data pelatihan tetapi tidak di data pengujian.
y_pred_test = model.predict(x_test) ##digunakan untuk mengevaluasi performa model pada data pengujian, yang memberikan gambaran tentang seberapa baik model akan bekerja pada data baru.

In [58]:
from sklearn.metrics import confusion_matrix, classification_report
print('evaluasi training')
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print('evaluasi testing')
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test)) ##laporan klasifikasi untuk data pelatihan menunjukkan metrik yang tinggi, 
##tetapi laporan untuk data pengujian menunjukkan metrik yang lebih rendah, ini dapat menunjukkan masalah overfitting.

evaluasi training
[[1 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 1]]
              precision    recall  f1-score   support

          28       1.00      1.00      1.00         1
          29       0.06      1.00      0.12         3
          31       0.50      0.50      0.50         2
          32       0.01      0.33      0.03         3
          33       0.06      0.50      0.11         2
          34       0.00      0.00      0.00         4
          35       0.00      0.00      0.00         9
          36       0.04      0.50      0.07         6
          37       0.06      0.71      0.12         7
          38       0.12      0.25      0.16        12
          39       0.00      0.00      0.00         9
          40       0.00      0.00      0.00        11
          41       0.00      0.00      0.00        17
          42       0.33      0.08      0.12        13
          43       0.00      0.00      0.00        

C:\Users\user\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda4\Lib\site-packages\sklearn\metrics\

In [41]:
data2 = pd.read_csv('R04_corruptions.csv')
data2 ##untuk data selanjutnya menggunakan perulangan yang sama

Corruption Perception (X)  Government Transparency (Y)
0                         3.2                           65
1                         2.5                           72
2                         4.1                           58
3                         2.8                           68
4                         3.5                           60
5                         2.4                           75
6                         3.9                           55
7                         2.7                           70
8                         3.8                           57
9                         2.9                           71
10                        4.2                           54
11                        2.6                           73
12                        3.0                           65
13                        2.3                           76
14                        4.0                           56
15                        3.4                           62
16                        2.2                           78
17                        4.3                           53
18                        3.3                           63
19                        2.1                           80
20                        4.4                           52
21                        3.7                           59
22                        2.0                           82
23                        4.5                           51
24                        3.6                           61
25                        2.8                           69
26                        4.2                           55
27                        3.1                           66
28                        2.7                           72
29                        4.3                           54
30                        3.9                           57
31                        2.5                           70
32                        4.4                           53
33                        3.0                           65
34                        2.6                           73
35                        4.1                           58
36                        3.2                           68
37                        2.4                           75
38                        4.5                           51
39                        3.5                           60
40                        2.9                           71
41                        3.8                           56
42                        2.3                           76
43                        4.0                           52
44                        3.4                           62
45                        2.2                           78
46                        4.4                           53
47                        3.3                           63
48                        2.1                           80
49                        4.3                           54
50                        3.7                           59
51                        2.0                           82
52                        4.5                           61
53                        3.6                           69
54                        2.8                           50

In [42]:
data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55 entries, 0 to 54
Data columns (total 2 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Corruption Perception (X)    55 non-null     float64
 1   Government Transparency (Y)  55 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 1012.0 bytes


In [50]:
categorical_features = [feature for feature in data2.columns
                       if data2[feature].dtypes == "0"]
data2[categorical_features]

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]

In [45]:
for i in categorical_features:
    print(data2[i].unique())

In [53]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()

for feature in categorical_features:
    print(data2[feature].unique())
    data2[feature] = label_encoder.fit_transform(data2[feature])
    print(data2[feature].unique())

In [62]:
x = data2.drop(['Corruption Perception (X)', 'Government Transparency (Y)'], axis = 1)
y = data2['Corruption Perception (X)']

In [63]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train, y_train)

GaussianNB()

In [64]:
from sklearn.metrics import confusion_matrix, classification_report
print('evaluasi training')
print(confusion_matrix(y_train, y_pred_train))
print(classification_report(y_train, y_pred_train))

print('evaluasi testing')
print(confusion_matrix(y_test, y_pred_test))
print(classification_report(y_test, y_pred_test))

evaluasi training
[[1 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 0 1]]
              precision    recall  f1-score   support

          28       1.00      1.00      1.00         1
          29       0.06      1.00      0.12         3
          31       0.50      0.50      0.50         2
          32       0.01      0.33      0.03         3
          33       0.06      0.50      0.11         2
          34       0.00      0.00      0.00         4
          35       0.00      0.00      0.00         9
          36       0.04      0.50      0.07         6
          37       0.06      0.71      0.12         7
          38       0.12      0.25      0.16        12
          39       0.00      0.00      0.00         9
          40       0.00      0.00      0.00        11
          41       0.00      0.00      0.00        17
          42       0.33      0.08      0.12        13
          43       0.00      0.00      0.00        

C:\Users\user\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda4\Lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\anaconda4\Lib\site-packages\sklearn\metrics\